(function(root){
'use strict';
const groups=[['高齢者',22,18,30,.75,2,.8,[1,2]],['子育て世帯',12,12,10,.55,1,1,[0,2]],['若者・独身',14,20,8,.35,0,1.5,[0,1]],['貧困層・非正規',10,12,9,.4,0,1.5,[4]],['富裕層・経営者',4,6,3,.7,3,.8,[3,5]],['労働組合員',8,7,6,.65,4,.8,[4,11]],['農林・地方自営',6,1,14,.8,4,.8,[7]],['都市無党派',14,17,8,.45,0,2,[6,10,11]],['保守活動層',3,2,4,.85,3,.8,[9]],['リベラル活動層',3,3,2,.85,3,.8,[8,10]],['宗教団体',2,2,3,.95,5,.5,[7,9]],['業界団体',2,1,3,.9,5,.5,[5,7]]];
const parties=[
{name:'国民保守党',tag:'地盤と組織の力',desc:'豊かな資金と地方の支持。長老のお願いには、逆らいにくい。',fame:15,money:800,likes:[30,0,-10,-5,25,-15,35,-5,30,-30,20,35],mod:[0,-5,5],ruling:true,leader:[.5,.5]},
{name:'都市改革党',tag:'信頼で風を起こす',desc:'都市の無党派が頼り。団体献金を受けると、党の処分を受ける。',fame:20,money:400,likes:[-10,15,25,5,15,-10,-25,30,5,0,-15,-15],mod:[0,5,-10],ruling:false,leader:[.3,.7]},
{name:'生活連帯党',tag:'暮らしを守る連帯',desc:'労働組合が選挙の土台。経営者への接近は、支持者を揺らす。',fame:10,money:500,likes:[10,20,5,20,-20,35,0,5,-15,20,-10,-10],mod:[0,0,0],ruling:false,leader:[.5,.5]},
{name:'正道党',tag:'小さく、固い結束',desc:'熱心な組織の支持が強み。その距離の近さを、無党派は見ている。',fame:10,money:600,likes:[10,15,-5,10,0,0,5,-15,5,-10,60,5],mod:[0,0,0],ruling:true,leader:[.7,.3]},
{name:'新風の会',tag:'風を味方につける',desc:'知名度は一歩リード。追い風も逆風も大きく、最後まで読めない。',fame:25,money:300,likes:[-5,5,20,20,-10,-15,5,15,15,-20,-10,-20],mod:[0,5,-5],ruling:false,leader:[.2,.8]}];
function population(s,i){return groups[i][1+s.district]/groups.reduce((sum,g)=>sum+g[1+s.district],0)*100000;}
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function random(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function log(s,text){s.logs.unshift({turn:s.turn,chapter:s.chapter||'prologue',text});s.logs=s.logs.slice(0,100)}
function change(s,effects,auto=false){const delta=Array(12).fill(0);for(const [i,x] of effects){delta[i]+=x*groups[i][6];if(auto&&x>0)for(const j of groups[i][7])delta[j]-=x*.4*groups[j][6]}delta.forEach((x,i)=>{if(x>0&&s.memory[i])x*=.5;s.likes[i]=clamp(s.likes[i]+x,-50,100)});}
function debt(s,i,weight=1){s.debts.push({id:s.debts.length,group:i,name:i<0?'党本部':groups[i][0],weight,chapter:s.chapter||'prologue',status:'未回収'});s.history.push({turn:s.turn,text:(i<0?'党本部':groups[i][0])+'への約束',kind:'接触',group:i,publicity:1});}
function create(p=0,d=0,name='新人候補',seed=Date.now()){const party=parties[p];const s={version:1,seed:seed>>>0,party:p,district:d,name:name.trim().slice(0,20)||'新人候補',turn:1,stage:'event',event:'start',fame:party.fame,speech:20,policy:20,network:10,energy:100,money:party.money,clean:80,influence:0,likes:party.likes.map(x=>clamp(x+party.mod[d],-50,100)),memory:Array(12).fill(false),org:Array(12).fill(0),visits:Array(12).fill(0),rival:groups.map((_,i)=>[12,8,5,8,12,10,15,8,8,5,5,12][i]),rivalFame:30,debts:[],history:[],logs:[],wind:0,nomination:'未公認',usedRescue:false,mandate:false,newBusiness:0,focus:0,policyStance:null,result:null,collection:[]};log(s,'選挙事務所を開設。12か月後の初選挙へ。');return s;}
function votes(s){let player=0,rival=0,total=0;const rows=[];groups.forEach((g,i)=>{const pop=population(s,i);const fixed=clamp(s.org[i],0,pop);const rivalFixed=clamp(s.rivalOrg?.[i]||0,0,pop-fixed);const remaining=pop-fixed-rivalFixed;const turnout=clamp(g[4]+Math.max(s.likes[i],s.rival[i])*.002,0,1);const cast=remaining*turnout;const a=clamp((s.likes[i]+20)/120)*Math.min(1,s.fame/60);const b=clamp((s.rival[i]+20)/120)*Math.min(1,s.rivalFame/60);const share=a+b?clamp(a/(a+b)+s.wind*.05,.02,.98):.5;const pv=fixed+cast*share,rv=rivalFixed+cast*(1-share);player+=pv;rival+=rv;total+=pv+rv;rows.push({population:pop,player:pv,rival:rv,fixed,rivalFixed});});return {player:Math.round(player),rival:Math.round(rival),total:Math.round(player)+Math.round(rival),share:player/total,rows};}
const actions=[['speech','街頭演説','知名度を広げ、弁舌を磨く。','体力 −15'],['visit','ミニ集会','選んだ支持層と話す。対立層は離れる。','体力 −12'],['org','団体訪問','組織票と資金。その代わりに約束。','体力 −10'],['network','後援会づくり','人脈と地元の支持を育てる。','資金 −50万 / 体力 −10'],['study','政策勉強会','政策力を磨き、別の解決策を探る。','体力 −8'],['media','メディア出演','弁舌次第で大きな注目、または炎上。','知名度30で解禁 / 体力 −15'],['sns','SNS発信','若者へ届ける。炎上の可能性も。','体力 −8'],['hq','党本部へ相談','資金と党内影響力。翌月は党務に。','体力 −8'],['rest','休養する','体力を35回復する。','体力回復'],['ad','選挙広告','資金を使い知名度を広げる。','資金 −100万 / 体力 −5']];
function campaign(s){if(s.chapter==='term'||s.chapter==='term2')return s.turn>=14;if(s.chapter==='term3')return s.turn===11||s.turn===12;if(s.chapter==='leadership'||s.chapter==='government')return false;return s.turn>=10;}
function allowed(s,id){return actions.some(a=>a[0]===id)&&s.stage==='main'&&!(s.mandate&&id!=='hq'&&id!=='rest')&&!(id==='media'&&s.fame<30)&&!(id==='network'&&s.money<50)&&!(id==='ad'&&(!campaign(s)||s.money<100))&&!(id==='hq'&&s.nomination==='無所属');}
function action(s,id,target=0,business=false){if(!allowed(s,id))return false;if(!Number.isInteger(target)||target<0||target>11)return false;if(id==='org'&&(groups[target][5]<3||s.memory[target]))return false;let cost={speech:15,visit:12,org:10,network:10,study:8,media:15,sns:8,hq:8,rest:0,ad:5}[id];if(cost===undefined)return false;const forced=s.mandate;s.mandate=false;const multi=campaign(s)?2:1;if(id==='rest'){s.energy=clamp(s.energy+35)}else{s.energy=clamp(s.energy-(root.Game.Campaign?.energyCost(s,id)??cost*multi))}
if(id==='speech'){s.fame+=3*[1,1.5,.7][s.district];s.speech+=1}
if(id==='visit')change(s,[[target,6*(s.district===1?.5:1)]],true);
if(id==='org'){s.visits[target]++;const donation=groups[target][5]*50*(business&&target===11?2:1);s.money+=donation;s.donationRefund=donation;change(s,[[target,8]],true);s.org[target]=population(s,target)*groups[target][5]*.1;if(groups[target][5]>=4)debt(s,target,s.visits[target]>=3?2:1);s.clean-=target===11?(business?8:3):target===10?5:2;if(business&&target===11)s.newBusiness++;s.history.push({turn:s.turn,text:groups[target][0]+'を訪問',kind:'接触',group:target,publicity:1});if(s.party===1&&s.nomination!=='無所属'){s.event='reform';}}
if(id==='network'){s.money-=50;s.network+=4;change(s,[[6,3],[2,-1]],false)}
if(id==='study')s.policy+=5;
if(id==='media'){if(random(s)<clamp((s.speech+20)/100,.1,.95)){s.fame+=8;log(s,'テレビ出演が好評。知名度が上がった。')}else{change(s,[[2,-8],[3,-8],[7,-8]]);log(s,'テレビで言葉に詰まる。無党派の期待がしぼんだ。')}}
if(id==='sns'){change(s,[[2,4],[0,-1]],false);s.fame+=2;if(random(s)<.1+(100-s.clean)/1000){change(s,[[2,-5],[7,-5]]);log(s,'SNSの投稿が炎上した。')}}
if(id==='hq'){s.influence+=4;s.money+=100;if(!forced)s.nextMandate=true;}
if(id==='ad'){s.money-=100;s.fame+=2}
root.Game.Campaign?.afterAction(s,id);for(const k of ['fame','speech','policy','network','clean','influence'])s[k]=clamp(s[k]);log(s,actions.find(a=>a[0]===id)[1]+(id==='visit'||id==='org'?'：'+groups[target][0]:''));const exhausted=s.energy===0;if(exhausted){s.energy=35;s.fame=clamp(s.fame-3);log(s,'体力が尽きた。週末を休養にあて、知名度が下がった。');}if(s.event==='reform'){s.stage='event';s.resume=exhausted||s.chapter==='term'||s.chapter==='term2'||s.chapter==='term3'?'finish':'weekend'}else if(exhausted||s.chapter==='term'||s.chapter==='term2'||s.chapter==='term3'){finishTurn(s)}else{s.stage='weekend'}return true;}
function weekend(s,id){if(s.stage!=='weekend'||!['festival','station','family','book'].includes(id))return false;if(id==='festival')change(s,[[6,2]],true);if(id==='station')s.fame=clamp(s.fame+1);if(id==='family')s.energy=clamp(s.energy+10);if(id==='book')s.policy=clamp(s.policy+1);log(s,'週末：'+{festival:'地元の祭り',station:'駅立ち',family:'家族との時間',book:'勉強'}[id]);finishTurn(s);return true;}
function finishTurn(s){if(s.chapter==='term'||s.chapter==='term2'||s.chapter==='term3')return root.Game.Legislature.finishTurn(s);const target=s.turn%3===0?s.likes.indexOf(Math.max(...s.likes)):s.rival.indexOf(Math.max(...s.rival));s.rival[target]=clamp(s.rival[target]+2,-50,100);s.rivalFame=clamp(s.rivalFame+1);s.wind=(random(s)*2-1)*(s.party===4?.9:.15);log(s,'対抗馬は'+groups[target][0]+'への働きかけを強めた。');s.mandate=!!s.nextMandate;s.nextMandate=false;if(s.turn===12){s.result=votes(s);s.result.won=s.result.player>s.result.rival;s.stage='result';return;}s.turn++;s.stage='event';s.event=({3:'nomination',5:'rival',6:'donation',8:'issue',9:'debate',10:'campaign',11:'scandal'})[s.turn]||null;if(s.event==='scandal'&&random(s)>=clamp((100-s.clean)*.005+s.newBusiness*.03,0,.95)){log(s,'記者の調査では大きな問題は見つからなかった。');s.event=null;}if(!s.event){const extra=root.Game.Extra?.pick(s);if(extra)s.event=extra;else if(random(s)<.15)s.event='festival';else s.stage='main';}}
function event(s){const c=(id,title,hint,disabled=false)=>({id,title,hint,disabled});switch(s.event){
case 'start':return {speaker:'秘書のタナカ',title:'最初の一票を、取りにいきましょう。',body:'あと12か月で投開票です。知名度を広げるか、支持者との約束を増やすか。党の公認は3か月目に決まります。',choices:[c('go','活動を始める','主行動を1つ、そのあと週末の行動を選びます')]};
case 'nomination':{const win=s.influence>=4||s.fame>=24;return {speaker:'党本部',title:win?'あなたを公認候補に決めました。':'今回は、別の候補を公認します。',body:win?'党の応援を受けて選挙へ進めます。ただし、当選を保証するものではありません。':'タナカ「無所属で戦うか、比例名簿に残るか。どちらにも代償があります」',choices:win?[c('official','公認を受ける','党の支援が続く')]:[c('independent','無所属で出る','党が得意な支持層が離れる／自由に活動できる'),c('list','比例下位で残る','惜敗すれば一度だけ復活の可能性／党への重い借り')]};}
case 'rival':return {speaker:'記者のサトウ',title:'対抗馬が、地元を固めています。',body:'相手は知名度で先行する地元の候補。毎月、得意な層を固め、ときどきあなたの支持層にも接近します。票読みは現在の情勢で、当選の保証ではありません。',choices:[c('go','活動を続ける','自分の支持層と知名度を確認する')]};
case 'donation':return {speaker:'後援会長のオオクボ',title:'「選挙には、お金がいるでしょう」',body:'業界団体から500万円の支援が届きました。受ければ人も集めてくれます。「当選したら、私たちのお願いも聞いてくださいね」',choices:[c('accept','支援を受ける','業界が喜ぶ／無党派が不信感を持つ／当選後に約束の回収',s.memory[11]),c('reject','きっぱり断る','無党派が喜ぶ／資金と組織票は得られない')]};
case 'issue':return {speaker:'地元の住民たち',title:'限られた予算を、誰のために。',body:'高齢者の通院支援と、保育所の増設。今の予算では両方を十分に支えられません。住民たちが、あなたの答えを待っています。',choices:[c('elder','通院支援を優先する','高齢者が喜ぶ／子育て世帯が怒る'),c('child','保育所を優先する','子育て世帯が喜ぶ／高齢者が怒る'),c('third','共同施設と送迎の再編を提案する','両方に少し届く／政策力40が必要',s.policy<40)]};
case 'debate':return {speaker:'公開討論会',title:'「あなたの言葉を、信じていいですか」',body:'対抗馬が、あなたの政策と団体との関係を問いただします。政策の一貫性を守るか、別の支持層に訴えるか。過去の約束は記録されています。',choices:[c('consistent','これまでの方針を説明する','弁舌で判定／過去の立場を守る'),c('switch','反対側の支持層に訴える','過去の公約があると、矛盾を突かれる')]};
case 'campaign':return {speaker:'秘書のタナカ',title:'選挙戦、最後の3か月です。',body:'活動の体力消費が2倍になります。資金を使う選挙広告も選べます。無理を重ねると、倒れて週末が休養になります。',choices:[c('go','選挙戦に入る','体力と資金の残りに気を配る')]};
case 'scandal':return {speaker:'記者のサトウ',title:'あなたをめぐる報道が出ました。',body:'過去の言動や支援者との距離に、疑問の声が上がっています。説明の仕方も、次の履歴として残ります。',choices:[c('apologize','謝って説明する','支持を失うが、今後の追及は弱まる'),c('explain','経緯を詳しく説明する','政策力で判定／成功なら被害が半分'),c('deny','問題はないと否定する','今の被害は小さい／当選後に虚偽発覚の可能性')]};
case 'reform':return {speaker:'都市改革党 本部',title:'「団体献金は、禁止のはずです」',body:'党が資金の受け取りを把握しました。返金して説明するか、党を離れて資金を持って戦うか、判断を求めています。',choices:[c('return','返金して説明する','資金を返す／党内影響力が下がる／組織との約束は残る'),c('leave','離党して選挙を続ける','無所属になる／党の支持層が離れる')]};
case 'festival':return {speaker:'後援会長のオオクボ',title:'「祭りで、一言お願いします！」',body:'地元の祭りで挨拶を頼まれました。予定は詰まっていますが、住民と顔を合わせる機会です。',choices:[c('yes','挨拶を引き受ける','地方が喜ぶ／少し疲れる'),c('no','今日は遠慮する','地方の期待が少し下がる')]};
case 'collect':{const d=s.debts[s.collection[0]];return {speaker:d.name+'からの連絡',title:d.group<0?'「次の採決は、党に従ってください」':'「当選したのだから、約束をお願いします」',body:d.group<0?'比例で助けた党から、方針への協力を求められました。地元の支持者とは意見が違います。':d.name+'が、自分たちを優先する政策への協力を求めています。応じれば、別の支持者に負担が回ります。',choices:[c('fulfill','約束を果たす',d.name+'が喜ぶ／対立する支持層が怒る'),c('partial','一部の協力にとどめる','資金200万円で調整／約束が1件残る',s.money<200),c('break','要求を断る','相手が離反／組織票を失う／信頼が戻りにくくなる')]};}
case 'after':return {speaker:'秘書のタナカ',title:'議員としての、最初の朝。',body:s.collection.length?'選挙中に助けてくれた人たちから、連絡が来ています。今回は重い約束から最大2件に向き合います。':'選挙中の支援に伴う借りはありません。自由に政策を選べますが、次の選挙の資金と地盤は自分で育てる必要があります。',choices:[c('go',s.collection.length?'連絡に答える':'これまでの歩みを見る','選挙の勝ち方が、その後の自由を変える')]};}
return null;}
function independent(s){s.nomination='無所属';s.likes=s.likes.map((x,i)=>parties[s.party].likes[i]>0?x-Math.max(0,x)*.5:x);s.mandate=false;s.nextMandate=false;}
function choose(s,id){if(s.stage!=='event')return false;const ev=event(s),opt=ev?.choices.find(c=>c.id===id);if(!opt||opt.disabled)return false;const type=s.event;log(s,ev.title+' → '+opt.title);s.event=null;
if(type==='nomination'){if(id==='official')s.nomination='公認';if(id==='independent')independent(s);if(id==='list')s.nomination='比例下位';}
if(type==='donation'){if(id==='accept'){s.money+=500;s.org[11]=Math.max(s.org[11],population(s,11)*.5);s.clean=clamp(s.clean-15);change(s,[[11,8],[2,-3],[3,-3],[7,-5]]);debt(s,11,2);if(s.party===1&&s.nomination!=='無所属'){s.event='reform';s.donationRefund=500;s.resume='main';return true;}}else{change(s,[[2,5],[3,5],[7,5]]);s.clean=clamp(s.clean+5);}}
if(type==='issue'){s.policyStance=id;change(s,id==='elder'?[[0,10],[1,-8]]:id==='child'?[[1,10],[0,-8]]:[[0,5],[1,5],[7,-3]]);s.history.push({turn:s.turn,text:opt.title,kind:'公約',group:id==='elder'?0:1,publicity:3});}
if(type==='debate'){const contradiction=id==='switch'&&s.policyStance!=='third';const chance=clamp((s.speech+35)/100-(contradiction?.1:0),.1,.95);if(random(s)<chance){change(s,groups.map((_,i)=>[i,3]));s.fame=clamp(s.fame+5);log(s,'討論会で説明が届いた。各層の評価が上がる。')}else{change(s,[[2,-5],[3,-5],[7,-5]]);log(s,'討論会で説明に苦しんだ。無党派の評価が下がる。')}if(contradiction){change(s,[[s.policyStance==='elder'?0:1,-5]]);s.history.push({turn:s.turn,text:'討論で過去の公約と矛盾',kind:'矛盾',publicity:3});}}
if(type==='scandal'){let m=id==='deny'?.3:id==='explain'?(random(s)<clamp((s.policy+20)/100,.1,.95)?.5:1.2):1;change(s,groups.map((_,i)=>[i,([2,3,7].includes(i)?-12:-5)*m]));if(id==='apologize')s.clean=clamp(s.clean-5);s.denied=id==='deny';s.history.push({turn:s.turn,text:opt.title,kind:'報道への対応',publicity:3});}
if(type==='festival'){change(s,[[6,id==='yes'?3:-2]],true);if(id==='yes')s.energy=clamp(s.energy-5);}
if(type==='reform'){if(id==='return'){s.money=Math.max(0,s.money-(s.donationRefund||250));s.influence=clamp(s.influence-5);s.clean=clamp(s.clean+5)}else independent(s);s.donationRefund=0;const resume=s.resume;s.resume=null;if(resume==='finish')finishTurn(s);else s.stage=resume||'main';return true;}
if(type==='after'){s.event=s.collection.length?'collect':null;s.stage=s.event?'event':'end';return true;}
if(type==='collect'){const d=s.debts[s.collection.shift()];if(id==='fulfill'){d.status='履行済み';if(d.group>=0)change(s,[[d.group,8]],true);else{change(s,[[2,-6],[7,-6]]);s.influence=clamp(s.influence+5)}}if(id==='partial'){s.money-=200;d.status='一部履行';d.weight=1;if(d.group>=0)change(s,[[d.group,-4]]);}if(id==='break'){d.status='踏み倒し';if(d.group>=0){change(s,[[d.group,-30]]);s.memory[d.group]=true;s.rivalOrg??=Array(12).fill(0);s.rivalOrg[d.group]+=s.org[d.group];s.org[d.group]=0;s.rival[d.group]=clamp(s.rival[d.group]+20,-50,100)}else{s.influence=clamp(s.influence-15);s.nominationCancelled=true;}}s.history.push({turn:13,text:d.name+'の要求：'+opt.title,kind:'借りの回収',publicity:3});s.event=s.collection.length?'collect':null;s.stage=s.event?'event':'end';return true;}
s.stage='main';return true;}
function continueResult(s,rescue=false){if(s.stage!=='result')return false;const eligible=s.nomination!=='無所属'&&!s.usedRescue&&s.result.share>=.42;if(!s.result.won&&!(rescue&&eligible)){s.stage='end';return true}if(!s.result.won){s.usedRescue=true;debt(s,-1,3)}s.elected=true;s.turn=13;if(s.denied&&random(s)<.4){change(s,[[2,-24],[3,-24],[7,-24]]);s.clean=clamp(s.clean-20);log(s,'当選後に虚偽が発覚。否定した報道が再燃した。')}s.collection=s.debts.filter(d=>d.status==='未回収').sort((a,b)=>b.weight-a.weight||a.id-b.id).slice(0,2).map(d=>d.id);s.stage='event';s.event='after';return true;}
const api={groups,parties,create,votes,actions,allowed,action,weekend,event,choose,continueResult,clamp,campaign,finishTurn,mechanics:{random,log,change,debt,population,independent}};root.Game=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
