'use strict';
// Forecast on copies with independent example outcomes; never consume the saved RNG.
const choiceForecastCache=new Map();
function choiceForecast(op,id,selectedTarget=0){
 const signature=JSON.stringify(state),key=[signature,op,id,selectedTarget,business].join('|');
 if(choiceForecastCache.has(key))return choiceForecastCache.get(key);
 if(choiceForecastCache.size>200)choiceForecastCache.clear();
 const fields=[['energy','体力'],['fame','知名度'],['speech','弁舌'],['policy','政策力'],['network','人脈'],['money','資金'],['clean','クリーン度'],['influence','党内影響力']];
 const outcomes=[];
 for(let example=0;example<8;example++){
  const copy=JSON.parse(signature);let draw=0;
  G.previewRandom.set(copy,()=>((example>>(draw++%3))&1)?.999999:0);
  const ok=op==='choice'?G.choose(copy,id):op==='weekend'?G.weekend(copy,id):G.action(copy,id,selectedTarget,business);
  if(ok)outcomes.push(copy);
 }
 const fmt=n=>(n>0?'+':'')+Number(n.toFixed(1));
 const parts=fields.flatMap(([field,label])=>{
  const values=outcomes.map(s=>s[field]-state[field]).filter(Number.isFinite);
  if(!values.length)return [];
  const lo=Math.min(...values),hi=Math.max(...values);if(!lo&&!hi)return [];
  return [label+(lo===hi?` ${fmt(lo)}${field==='money'?'万円':''}`:lo<0&&hi>0?' ↑↓':hi>0?' ↑の可能性':' ↓の可能性')];
 });
 const result=outcomes.length?(parts.length?'変化の目安：'+parts.join(' / '):'主要能力・資金の変化なし（支持・約束は説明参照）'):'必要条件を満たすと選べます';
 choiceForecastCache.set(key,result);return result;
}
const actionLook={staff:['👥','スタッフに委託','purple'],publicity:['📢','党の広報強化','orange'],outreach:['🤝','地域交流','orange'],donors:['💌','個人サポーター募集','green'],practice:['🎤','スピーチ練習','blue'],speech:['📣','街頭演説','blue'],visit:['🤝','ミニ集会','orange'],org:['🏢','団体訪問','purple'],network:['🙌','後援会づくり','orange'],study:['📚','政策の勉強','blue'],media:['📺','テレビ出演','pink'],sns:['📱','SNS発信','pink'],hq:['🏛️','党本部へ','purple'],rest:['🍵','ひと休み','green'],ad:['🪧','選挙広告','orange'],question:['🎤','国会で質問','blue'],committee:['📋','委員会活動','blue'],local:['🏘️','地元で活動','orange'],faction:['👥','派閥の会合','purple'],abroad:['✈️','海外視察','green'],study_group:['📓','勉強会立ち上げ','purple'],stump:['📣','応援演説','orange'],policy:['📜','看板政策','blue'],diplomacy:['🌐','外遊・首脳会談','green'],presser:['🎙️','記者会見','pink'],faction_care:['🤝','派閥への配慮','purple'],tighten:['🪢','党内引き締め','purple'],dissolve:['🗳️','衆議院を解散','orange']};
const actionGroups=[{id:'funds',label:'資金・仲間',icon:'🤝',ids:['staff','donors','outreach','network','ad']},{id:'town',label:'まちで活動',icon:'📣',ids:['speech','visit','org','sns','local']},{id:'self',label:'自分を育てる',icon:'📚',ids:['study','media','abroad','ad','practice']},{id:'party',label:'党・議会',icon:'🏛️',ids:['hq','network','question','committee','faction','study_group','stump']}];
let actionGroup='town',inspector='support',pendingAction=null,transition=null,effectAnimation=null;
function header(){return `<header class="topbar"><div class="brand"><span aria-hidden="true">★</span> 政治家になろう<span class="brand-bang">！</span></div><div class="header-right"><span class="edition">${state?'自動セーブ':'試作版 0.6'}</span>${state?'<button class="quiet" data-do="reset">はじめから</button>':''}</div></header>`;}
function setup(){return `<section class="new-game"><div class="setup-intro"><div><span class="chapter-chip">新人候補、いよいよデビュー！</span><h1>あなたの政治家ライフを<br>はじめよう！</h1><p>街で話して、勉強して、ときにはひと休み。<br>まずは最初の当選をめざそう！</p></div><div class="setup-route"><span>📣<b>出馬準備</b></span><i>➜</i><span>🗳️<b>初めての選挙</b></span><i>➜</i><span>🏛️<b>議員生活へ！</b></span></div></div>
 <h2 class="section-title"><span>1</span> 所属する政党を選ぼう</h2><div class="party-grid">${G.parties.map((p,i)=>`<button class="party ${i===party?'selected':''}" data-do="party" data-id="${i}" aria-pressed="${i===party}" style="--party-color:${['#228ad6','#13a8a0','#ef8739','#9764cc','#e95e82'][i]}"><div class="party-symbol" aria-hidden="true">${['🏘️','🌟','🤝','🌱','🌈'][i]}</div><h3>${p.name}</h3><b class="party-tag">${p.tag}</b><p>${p.desc}</p><div class="party-start">知名度 <strong>${p.fame}</strong> <span>資金 <strong>${p.money}</strong>万</span></div><span class="party-check">${i===party?'✓ 選択中':'この党を選ぶ'}</span></button>`).join('')}</div>
 <div class="setup-bottom"><div><h2 class="section-title"><span>2</span> 名前と選挙区を決めよう</h2><div class="fields"><div><label for="candidate">あなたの名前</label><input id="candidate" maxlength="20" value="${esc(draftName)}" placeholder="新人候補" autocomplete="off"></div><div><label for="district">選挙区</label><select id="district"><option value="0" ${district===0?'selected':''}>混合区：いろいろな人が暮らす街</option><option value="1" ${district===1?'selected':''}>都市区：若者と無党派が多い街</option><option value="2" ${district===2?'selected':''}>地方区：地元のつながりが強い街</option></select></div></div></div><button class="primary start-button" data-do="start">この街でスタート！ <span>▶</span></button></div><p class="footnote">進行はこのブラウザに自動保存されます。架空の政党・人物によるフィクションです。</p></section>`;}
function visualValue(key,index){if(!effectAnimation)return index===undefined?state[key]:state[key][index];const start=index===undefined?effectAnimation.before[key]:effectAnimation.before[key][index],end=index===undefined?state[key]:state[key][index];return start+(end-start)*effectAnimation.progress;}
function hud(){return `<section class="hud" aria-label="あなたの能力">${[['energy','体力','♥','green'],['fame','知名度','★','orange'],['speech','弁舌','●','pink'],['policy','政策力','◆','blue'],['network','人脈','✦','purple']].map(([key,label,icon,color])=>{const value=visualValue(key);return `<div class="hud-stat ${color} ${effectAnimation?.changed.has(key)?'changing':''}"><div><span>${icon} ${label}</span><strong>${num(value)}<small>/100</small></strong></div><div class="meter"><i style="width:${G.clamp(value)}%"></i></div></div>`;}).join('')}<div class="hud-money ${effectAnimation?.changed.has('money')?'changing':''}"><span>💰 活動資金</span><strong>${num(visualValue('money'))}<small>万円</small></strong></div></section>`;}
function calendar(){
 const stage=state.stage;
 if(leadership()){return `<div class="calendar"><div><span class="chapter-chip">党首選 · CANDIDACY</span><strong>${state.leaderResult?.ending?'開票':state.leaderResult?'決選投票へ':'選挙戦'}</strong><small>議員票と党員票の争い</small></div><div class="turn-steps" aria-label="現在の進行"><span class="current">1 選挙戦</span><span>2 開票</span></div></div>`;}
 if(government()){const ph=state.govPhase;return `<div class="calendar"><div><span class="chapter-chip">終章 · PRIME MINISTER</span><strong>${ph==='cabinet'?'組閣':ph==='ended'?'審判':state.turn+'期目 / 16'}</strong><small>${ph==='run'?'支持率 '+num(state.approval)+'% ／ 派閥の不満 '+num(state.factionAnger):ph==='cabinet'?'内閣の顔ぶれを決める':'政権の評価'}</small></div><div class="turn-steps" aria-label="現在の進行"><span class="${ph==='cabinet'?'current':''}">1 組閣</span><span class="${ph==='run'&&stage==='main'?'current':''}">2 政権運営</span><span class="${ph==='ended'||stage==='end'?'current':''}">3 審判</span></div></div>`;}
 const count=maximum(),current=Math.min(state.turn,count);
 const chip=state.chapter==='term3'?'第3期 · 党の顔':state.chapter==='term2'?'第2期 · 中堅議員':state.chapter==='term'?'第1期 · 議員生活':'序章 · 出馬準備';
 const yearBase=state.chapter==='term3'?8:state.chapter==='term2'?4:0;
 return `<div class="calendar"><div><span class="chapter-chip">${chip}</span><strong>${term()?`${yearBase+Math.floor((state.turn-1)/4)+1}年目 / 第${(state.turn-1)%4+1}四半期`:state.turn===13?'初当選！':`${state.turn}か月目`}</strong><small>${current} / ${count}${term()?'ターン':'か月'}</small></div><div class="turn-steps" aria-label="現在の進行">${(term()?['イベント','活動','次の3か月へ']:['イベント','活動','週末']).map((label,i)=>`<span class="${(i===0&&stage==='event'||i===1&&stage==='main'||i===2&&stage==='weekend')?'current':''}">${i+1} ${label}</span>`).join('')}</div></div>`;}
function scene(){const asset=window.GameScenes.resolve(state);return `<div class="scene" data-scene="${esc(state.event||state.stage)}"><div class="scene-art">${asset.src?`<img src="${esc(asset.src)}" alt="${esc(asset.alt)}" width="1672" height="941" fetchpriority="high">`:'<div class="scene-text"><span>さあ、今日も一歩前へ！</span></div>'}</div><span class="location">📍 ${esc(asset.label)}</span><span class="scene-goal">${government()?'めざせ、国民の総理！':leadership()?'めざせ、党首の座！':state.chapter==='term3'?'めざせ、与党第一党！':term()?'めざせ、再選！':'めざせ、初当選！'}</span></div>`;}
function dialogue(speaker,title,body){return `<div class="dialogue"><div class="speaker">${esc(speaker)}</div><h2>${esc(title)}</h2><p>${esc(body)}</p></div>`;}
function checkUI(op,id){
 const c=G.choiceCheck(state,op,id);if(!c)return '';
 const pct=n=>+(n*100).toFixed(1);
 return `<span class="check-hint"><strong>🎲 成功 ${pct(c.chance)}% ／ 失敗 ${pct(1-c.chance)}%${c.risk?'（炎上リスク）':''}</strong><small>${esc(c.label)}${c.value==null?'':' '+num(c.value)}${c.penalty?' ／ 矛盾による補正 −'+c.penalty+'ポイント':''}</small><small>成功：${esc(c.success)} ／ 失敗：${esc(c.failure)}</small></span>`;
}
function eventUI(){const ev=G.event(state);if(!ev)return '<div class="notice">イベントを読み込めませんでした。</div>';return `${dialogue(ev.speaker,ev.title,ev.body)}${personRibbon()}<div class="choice-area"><div class="prompt-label">どうする？ <span>選択肢を1つ選ぼう</span></div><div class="choices">${ev.choices.map((c,i)=>`<button class="choice" data-do="choice" data-id="${esc(c.id)}" ${c.disabled?'disabled':''}><b><span class="choice-number">${i+1}</span>${esc(c.title)}</b><span>${esc(c.hint)}</span>${checkUI("choice",c.id)}<span class="choice-effects">${esc(choiceForecast("choice",c.id))}</span></button>`).join('')}</div></div>`;}
function actionCost(id,cost){const energy=G.Campaign.energyCost(state,id),gain=G.Campaign.fameGain(state,id);return (id==='rest'?'体力 +35':`体力 −${energy}${G.actionFunds(state,id)?' / '+G.actionFunds(state,id)+'万円':''}`)+(gain?` / 知名度 +${Number(gain.toFixed(2))}`:'');}
function actionCard(a){const [id,title,desc,cost]=a,[icon,short,color]=actionLook[id];const locked=!G.allowed(state,id);const reason=id!=='rest'&&state.energy===0?'体力切れです。休養が必要':state.money<G.actionFunds(state,id)?'資金が足りません':id==='media'&&state.fame<30?'知名度30から':(id==='ad'||id==='stump')&&!G.campaign(state)?'選挙運動で解放':state.chapter!=='term2'&&(id==='study_group'||id==='stump')?'第2期で解放':id==='ad'&&state.money<G.funds(state,100)?'資金が足りません':id==='network'&&state.money<G.funds(state,50)?'資金が足りません':id==='study_group'&&state.money<G.funds(state,100)?'資金が足りません':id==='faction'?'派閥への所属が必要':state.mandate?'今回は党務か休養を選ぼう':'今は選べません';return `<button class="action ${color}" data-do="${['visit','org','question'].includes(id)?'pickAction':'action'}" data-id="${id}" ${locked?'disabled':''} title="${esc(desc)}"><span class="action-icon" aria-hidden="true">${icon}</span><span class="action-copy"><b>${short}</b><small>${locked?reason:esc(desc)}</small>${locked?'':checkUI('action',id)}<em>${locked?'🔒 ':''}${actionCost(id,cost)}</em><small class="choice-effects">${locked?'':esc(choiceForecast('action',id,target))}</small></span></button>`;}
function targetPicker(){const a=G.actionsFor(state).find(a=>a[0]===pendingAction);if(!a)return '';const blocked=pendingAction==='org'&&(G.groups[target][5]<3||state.memory[target]);return `<div class="target-picker"><button class="quiet" data-do="cancelAction">‹ 行動選びに戻る</button><h3>${actionLook[pendingAction][0]} ${a[1]}：誰に会う？</h3><div class="target-options">${G.groups.map((g,i)=>{const no=pendingAction==='org'&&(g[5]<3||state.memory[i]);return `<button class="target ${target===i?'selected':''}" data-do="target" data-id="${i}" aria-pressed="${target===i}" ${no?'disabled':''}>${g[0]}<small>${no?(state.memory[i]?'関係が破綻':'団体訪問の対象外'):`好感度 ${num(state.likes[i])}`}</small></button>`;}).join('')}</div>${pendingAction==='org'&&target===11?`<label for="business">訪問する団体<select id="business"><option value="0" ${!business?'selected':''}>伝統業界</option><option value="1" ${business?'selected':''}>新興ビジネス</option></select></label>`:''}<div class="target-footer"><p>${esc(a[2])}${checkUI("action",pendingAction)}<br><b>${actionCost(pendingAction,a[3])}</b><br><span class="choice-effects">${esc(choiceForecast('action',pendingAction,target))}</span></p><button class="primary" data-do="action" data-id="${pendingAction}" ${blocked?'disabled':''}>${G.groups[target][0]}へ！ ▶</button></div></div>`;}
function mainUI(){const all=G.actionsFor(state);const group=actionGroups.find(g=>g.id===actionGroup);const allowedIds=new Set(group.ids.concat('rest'));return `${state.mandate?'<div class="mandate-notice"><b>🏛️ 今回は党務の月です</b><span>「党本部へ相談」か「ひと休み」を選んでください</span></div>':''}${dialogue('秘書のタナカ',term()?'この3か月、何に力を注ぐ？':'今月、何に力を注ぐ？',state.mandate?'今回は党のお仕事をする約束です。疲れていたら、休養も選べます。':state.energy<25?'少しお疲れのようですね。ひと休みするのも、大切な活動ですよ！':term()?'議会での仕事も、地元とのつながりも大切です。活動を1つ選んで進めましょう！':'街の人に会う？ それとも自分を磨く？ 今日の活動を1つ選びましょう！')}
 <div class="action-area">${pendingAction?targetPicker():`<div class="action-tabs" role="tablist" aria-label="行動の種類">${actionGroups.map(g=>`<button role="tab" aria-selected="${actionGroup===g.id}" data-do="actionGroup" data-id="${g.id}" class="${actionGroup===g.id?'selected':''}">${g.icon} ${g.label}</button>`).join('')}</div><div class="actions" role="tabpanel" aria-label="${group.label}">${all.filter(a=>allowedIds.has(a[0])).map(actionCard).join('')}</div><p class="growth-tip">育成イベントの目標：知名度35・65／弁舌35・65／政策力40・65／人脈25・55（採決のある回でも成長イベント発生・各1回）</p><p class="action-tip">${term()?'活動を選ぶと3か月進みます。':'活動のあとは、週末の過ごし方を選びます。'}${G.campaign(state)?' 選挙運動中は体力消費2倍！':''}</p>`}</div>`;}
function weekendUI(){return `${dialogue('秘書のタナカ','今週も、おつかれさまでした！','週末はどう過ごしましょう？ あと1つ選ぶと、次の月に進みます。')}<div class="choice-area"><span class="eyebrow">WEEKEND / 週末の過ごし方</span><div class="weekend-actions">${[['festival','🏮','地元の祭りへ','地方の支持が上がる／都市の支持が少し下がる'],['station','📣','駅に立つ','知名度 +1'],['family','🏠','家族と過ごす','体力 +10'],['book','📖','本を読む','政策力 +1']].map(([id,icon,title,hint])=>`<button class="choice" data-do="weekend" data-id="${id}"><b>${icon} ${title}</b><span>${hint}</span><span class="choice-effects">${esc(choiceForecast("weekend",id))}</span></button>`).join('')}</div></div>`;}
function govMainUI(){
 const p=state.platform!=null?G.Legislature.platforms[state.platform]:null;
 return `${dialogue('秘書のタナカ','今期は、何に手をつけますか。',`支持率 ${num(state.approval)}% ／ 派閥の不満 ${num(state.factionAnger)}${state.factionAnger>10?'（倒閣リスク）':''}。看板政策はあと${3-state.policyPushed}本、任期は残り${16-state.turn+1}期。`)}
 <div class="action-area"><div class="actions gov-actions" role="tabpanel" aria-label="政権の行動">${G.actionsFor(state).map(a=>{
  const [id,title,desc]=a,[icon,,color]=actionLook[id]||['⭐',title,'blue'];const locked=!G.allowed(state,id);
  const detail=state.money<G.actionFunds(state,id)?'資金が足りません':id==='policy'?(state.policyPushed>=3?'今期はもう提出できません':(p?`「${p.name}」を提出：${G.groups[p.benefit[0]][0]}ら＋／${G.groups[p.burden[0]][0]}ら−`:desc)):desc;
  return `<button class="action ${color}" data-do="action" data-id="${id}" ${locked?'disabled':''} title="${esc(desc)}"><span class="action-icon" aria-hidden="true">${icon}</span><span class="action-copy"><b>${esc(title)}</b><small>${esc(detail)}${G.actionFunds(state,id)?' ／ 費用 '+G.actionFunds(state,id)+'万円':''}</small>${locked?'':checkUI("action",id)}<small class="choice-effects">${locked?'':esc(choiceForecast("action",id))}</small></span></button>`;
 }).join('')}</div><p class="action-tip">S評価には4期以上の運営と政策成立が必要です。解散すれば、そのターンで最終選挙へ。</p></div>`;
}
const transitionLook={staff:['👥','スタッフが活動中！','チームで地域の声を集めています','meet'],publicity:['📢','広報チームが活動中！','党の政策を伝えています','talk'],outreach:['🤝','地域で交流中！','新しい仲間と話しています','meet'],donors:['💌','サポーターを募集中！','小さな応援を集めています','work'],practice:['🎤','スピーチを練習中！','伝える力を磨いています','talk'],
 speech:['📣','街頭演説中！','声を届けています','talk'],visit:['🤝','ミニ集会中！','じっくり対話しています','meet'],org:['🏢','団体を訪問中！','支援の輪を広げています','meet'],network:['🙌','後援会づくり中！','仲間が集まっています','meet'],study:['📚','政策を勉強中！','資料を読み込んでいます','study'],media:['📺','テレビ出演中！','カメラの前で話しています','talk'],sns:['📱','SNSで発信中！','投稿を作っています','type'],hq:['🏛️','党本部で相談中！','作戦を練っています','meet'],rest:['🍵','ひと休み中…','しっかり回復しています','rest'],ad:['🪧','選挙広告を準備中！','街へ届けています','work'],question:['🎤','国会で質問中！','答弁を引き出しています','talk'],committee:['📋','委員会で審議中！','政策を詰めています','study'],local:['🏘️','地元を訪問中！','地域の声を聞いています','walk'],faction:['👥','派閥の会合中！','人脈を築いています','meet'],abroad:['✈️','海外を視察中！','新しい政策を学んでいます','walk'],study_group:['📓','勉強会を準備中！','仲間の議員に声をかけています','meet'],stump:['📣','応援演説中！','仲間の候補を応援しています','talk'],policy:['📜','法案を審議中！','看板政策を通そうとしています','study'],diplomacy:['🌐','首脳会談中！','各国と交渉しています','walk'],presser:['🎙️','記者会見中！','国民へ説明しています','talk'],faction_care:['🤝','派閥と調整中…','ポストと予算を割り振っています','meet'],tighten:['🪢','党内を引き締め中…','結束を確かめています','meet'],dissolve:['🗳️','解散を表明！','国民に信を問います','talk'],festival:['🏮','お祭りに参加中！','地域のみんなと交流しています','dance'],station:['📣','駅前で活動中！','通勤中の人へ挨拶しています','talk'],family:['🏠','家族と団らん中…','心も体も回復しています','rest'],book:['📖','読書中…','知識を蓄えています','study']
};
const chapterIntros={
 prologue:['CHAPTER 0','序章','出馬準備','まずは、初めての当選をめざそう。'],
 term:['CHAPTER 1','第1期','議員生活','一票の重みを背負い、国会へ。'],
 term2:['CHAPTER 2','第2期','中堅議員','実績を積み、党を動かす存在へ。'],
 term3:['CHAPTER 3','第3期','党の顔','党の未来と、政権を懸けた戦いへ。'],
 leadership:['CHAPTER 4','党首選','頂点への挑戦','議員と党員の信頼を集め、党の代表へ。'],
 government:['FINAL CHAPTER','終章','内閣総理大臣','この国の行方を、その手に。']
};
function transitionUI(){
 if(transition.kind==='chapter'||transition.kind==='start'){
  const c=chapterIntros[transition.chapter]||chapterIntros.prologue;
  return `<div class="chapter-intro ${transition.kind==='start'?'title-loader':''} transition-screen" role="status" aria-live="polite"><div class="title-rays" aria-hidden="true"></div>${transition.kind==='start'?'<div class="loading-title"><span>★</span><b>政治家になろう<i>！</i></b></div>':''}<div class="chapter-number">${c[0]}</div><h1>${c[1]}</h1><h2>${c[2]}</h2><p>${c[3]}</p><div class="chapter-line" aria-hidden="true"><i></i><span>★</span><i></i></div><div class="loading-dots" aria-label="次の章を準備中"><i></i><i></i><i></i></div>${transition.kind==='start'?'<small class="chapter-loading-copy">選挙事務所を準備しています</small>':''}</div>`;
 }
 const [icon,title,body,motion]=transitionLook[transition.id]||['⭐','活動中！','次の場面を準備しています','work'];return `<div class="transition-screen" role="status" aria-live="polite"><div class="transition-sun" aria-hidden="true"></div><div class="transition-stage motion-${motion}" aria-hidden="true"><span class="mini-shadow"></span><span class="mini-person"><i class="mini-head">😊</i><i class="mini-body">${icon}</i></span><span class="mini-tanaka"><i>👩🏻</i><b>📋</b></span><span class="motion-mark">${motion==='walk'?'💨':motion==='rest'?'♪':'✨'}</span></div><h2>${title}</h2><p>${body}</p><div class="loading-dots" aria-label="次の場面を準備中"><i></i><i></i><i></i></div></div>`;
}
function supportPanel(){const likes=state.likes.map((_,i)=>visualValue('likes',i)),forecastState=effectAnimation?{...state,likes}:state,v=G.votes(forecastState);return `<div class="forecast"><div><span>いまの得票予想</span><strong>${(v.share*100).toFixed(1)}<small>%</small></strong></div><div class="forecast-meter"><i style="width:${v.share*100}%"></i><b></b></div><small>あなた ${num(v.player)}票 / 相手 ${num(v.rival)}票</small></div><div class="support-list">${G.groups.map((g,i)=>{const value=likes[i];return `<div class="support ${effectAnimation?.changed.has('likes.'+i)?'changing':''}"><div class="support-top"><span>${g[0]}${state.org[i]?' ▪':''}${state.rivalOrg?.[i]?' ◆':''}</span><b class="${value<0?'negative':'positive'}">${value>0?'+':''}${num(value)}</b></div><div class="support-meter"><i class="${value<0?'negative':'positive'}" style="width:${Math.abs(value)/2}%;left:${value<0?50-Math.abs(value)/2:50}%"></i></div></div>`;}).join('')}</div><p class="footnote">好感度 −50〜100。▪ 自分の組織票 / ◆ 相手の組織票。予想は活動によって変わります。</p>`;}
function budgetUI(){const b=G.budget(state);return `<div class="budget-strip">活動規模 ×${G.scale(state)}${b.income?` ／ ${government()?'毎期':'3か月ごと'}：個人支援 ＋${b.income}万・維持費 −${b.expense}万（差引 ＋${b.net}万）`:''}${state.chapter==='government'?' ／ 党の活動資金（国家予算とは別）':''}</div>`;}
function personRibbon(){const p=G.People?.forEvent(state);if(!p)return '';const r=p.relation,v=G.People.status(r);return `<div class="person-ribbon" aria-label="本人との関係"><b>${esc(p.profile.name)} · ${p.stage}/4</b><span>信頼 ${r.trust}</span><span>政策への賛否 ${r.agreement>0?'+':''}${r.agreement}</span><span>生活 ${r.life}</span><small>${esc(v.agreement)} ／ 支持層全体とは別の数値</small></div>`;}
function peoplePanel(){const rows=G.People?.entries(state)||[];return `<h3>出会った人たち</h3><p class="people-note">信頼していても、政策には反対かもしれません。一人との関係は、層全体の支持とは別です。</p>${rows.length?rows.map(r=>{const p=G.People.profiles.find(x=>x.id===r.id),v=G.People.status(r);return `<section class="person-card"><img src="assets/people/${p.id}.webp" alt="${esc(p.alt)}" loading="lazy"><h3>${esc(p.name)}</h3><p>${esc(p.job)}</p><dl><div><dt>信頼</dt><dd>${r.trust}/100 · ${esc(v.trust)}</dd></div><div><dt>政策への賛否</dt><dd>${r.agreement>0?'+':''}${r.agreement} · ${esc(v.agreement)}</dd></div><div><dt>生活</dt><dd>${r.life}/100 · ${esc(v.life)}</dd></div></dl><details><summary>${r.stage===4?'関係の歩み':'これまでのやりとり'} ${r.stage}/4</summary>${r.history.map(h=>`<p>${esc(period(h.turn,h.chapter))}<br>${esc(h.label)}</p>`).join('')}</details></section>`;}).join(''):'<p>まだ出会いはありません。支持の弱い層の相談者と、活動中に出会います。</p>'}`;}
function contracts(){const p=G.Campaign.current(state);if(!p)return [];const rows=[];
 if(p.consultant>0)rows.push({icon:'📋',title:'選挙コンサル',count:p.consultant,detail:'演説・SNS・広告の知名度効果＋50%／消費体力−25%'});
 if(p.influencer>0)rows.push({icon:'📱',title:'コラボ配信',count:p.influencer,detail:'毎回知名度＋3'+(p.influencerMode==='provocative'?'／毎回25%で炎上':'／政策紹介・炎上なし')});
 return rows;}
function contractStrip(){const rows=contracts(),p=G.Campaign.current(state);if(!rows.length&&!(p?.party==='large'&&!p.sponsorResolved))return '';return `<div class="contract-strip" aria-label="契約の残り回数">${rows.map(r=>`<span title="${esc(r.detail)}">${r.icon} ${r.title} <b>あと${r.count}回</b></span>`).join('')}${p?.party==='large'&&!p.sponsorResolved?'<span>🤝 業界への約束あり</span>':''}<button data-do="inspector" data-id="debt">効果・約束を見る</button></div>`;}
function debtPanel(){const rows=contracts(),p=G.Campaign.current(state);return `${rows.length?'<h3>進行中の契約</h3>'+rows.map(r=>`<div class="contract-detail"><b>${r.icon} ${r.title}：あと${r.count}回</b><p>${r.detail}</p><small>休養を含む主行動で1回消費。週末・イベント回答では消費しません。</small></div>`).join(''):''}<h3>支援者との約束</h3>${state.debts.length?state.debts.map(d=>`<div class="debt"><b>${esc(d.name)}</b><span class="badge">${d.status}</span><p>約束の重さ ${'★'.repeat(d.weight)}</p>${d.id===G.Campaign.current(state)?.sponsorDebt&&d.status==='未回収'?`<p>選挙前に業界優先の公約を要求。断る場合は${p?.refundDue??150}万円返金か支援撤回。</p>`:''}</div>`).join(''):'<div class="empty"><span>🤝</span><h3>まだ約束はありません</h3><p>支援を受けると、ここに記録されます。</p></div>'}<p class="footnote">支援者への約束は、当選後の活動にもつながります。</p>`;}
function records(){return `<h3>最近のできごと</h3><div class="log-scroll">${state.logs.slice(0,25).map(l=>`<div class="history"><small>${period(l.turn,l.chapter)}</small><p>${esc(l.text)}</p></div>`).join('')}</div><details><summary>採決・発言・接触の履歴 ${state.history.length}件</summary>${state.history.slice().reverse().map(h=>`<div class="history"><small>${period(h.turn,h.chapter)} / ${esc(h.kind)}</small><p>${esc(h.text)}</p></div>`).join('')||'<p>まだ記録はありません。</p>'}</details>`;}
function inspectorUI(){return `<aside class="inspector"><div class="player-mini"><span class="player-icon" aria-hidden="true">😊</span><div><b>${esc(state.name)}</b><small>${state.nomination==='無所属'?'無所属':G.parties[state.party].name} / ${['混合区','都市区','地方区'][state.district]}</small></div></div><div class="inspector-tabs" role="tablist" aria-label="陣営の情報">${[['support','支持'],['debt','約束'],['records','記録'],['people','人物']].map(([id,label])=>`<button role="tab" aria-selected="${inspector===id}" data-do="inspector" data-id="${id}" class="${inspector===id?'selected':''}">${label}${id==='debt'?`<small>${state.debts.filter(d=>['未回収','一部履行'].includes(d.status)).length}</small>`:''}</button>`).join('')}</div><div class="inspector-content ${inspector}" role="tabpanel" aria-label="${{support:'支持',debt:'約束',records:'記録',people:'人物'}[inspector]}">${inspector==='support'?supportPanel():inspector==='debt'?debtPanel():inspector==='people'?peoplePanel():records()}</div><details class="internal"><summary>くわしい状態</summary><p>クリーン度 ${num(state.clean)} / 党内影響力 ${num(state.influence)}<br>公認：${esc(state.nomination)}${term()||leadership()?`<br>委員会：${state.committee===null?'未定':G.Legislature.committees[state.committee].name}<br>採決 ${state.ballots.length} / 8本${state.chapter==='term2'?`<br>役職：${state.viceMinister?'副大臣':state.role&&state.role!=='none'?state.role:'なし'}`:''}${state.chapter==='term3'||leadership()?`<br>役職：${state.cabinet==='minister'?'大臣':state.cabinet==='exec'?'党三役':'なし'}${state.chapter==='term3'?`<br>党の立場：${state.ruling?'与党':'野党'}`:''}${state.platform!=null?`<br>看板政策：${esc(G.Legislature.platforms[state.platform].name)}`:''}`:''}` :''}${government()?`<br>支持率：${num(state.approval??0)}% / 派閥の不満：${num(state.factionAnger)}<br>看板政策：${state.platform!=null?esc(G.Legislature.platforms[state.platform].name):'未定'}（成立 ${state.policyPushed} / 3）<br>組閣：${state.cabinetPlan==='merit'?'実力重視':state.cabinetPlan==='balance'?'派閥均衡':state.cabinetPlan==='renew'?'刷新':'—'}`:''}</p></details></aside>`;}
function effectUI(){return effectAnimation?`<div class="effect-feedback ${effectAnimation.progress?'applying':'revealing'}" role="status" aria-live="assertive"><b>選択の結果</b>${(effectAnimation.results||[]).map(r=>`<section class="check-result ${r.success?'success':'failure'}"><h2>${r.success?'✓ 成功！':'× 失敗…'}</h2><b>${esc(r.title)}</b><p>${esc(r.text)}</p></section>`).join('')}<div>${effectAnimation.items.map(item=>`<span class="${item.delta>0?'up':'down'}"><i>${item.icon}</i>${esc(item.label)} <strong>${item.delta>0?'+':''}${num(item.delta)}${item.unit||''}</strong></span>`).join('')}</div></div>`:'';}
function render(){const preservedCelebration=document.querySelector?.('.victory-celebration'),previousCelebrationKey=celebrationKey;if(!state)celebrationKey=null;const previousFocus=document.activeElement?.id;app.innerHTML=header()+`<main class="wrap">${storageWarning?`<div role="status" class="notice">${esc(storageWarning)}</div>`:''}${!state?setup():`${calendar()}${hud()}<div class="game-layout"><section class="game-center" id="game-content" tabindex="-1">${transition?transitionUI():state.stage==='result'?resultUI():state.stage==='end'?endUI():`<div class="stage-frame stage-${esc(state.stage)}">${contractStrip()}${budgetUI()}${scene()}${state.stage==='event'?eventUI():state.stage==='main'?(government()?govMainUI():mainUI()):weekendUI()}</div>`}</section>${inspectorUI()}</div>${effectUI()}`}</main>`;const replacement=document.querySelector?.('.victory-celebration');if(preservedCelebration&&replacement&&previousCelebrationKey===celebrationKey)replacement.replaceWith(preservedCelebration);if(previousFocus)document.getElementById(previousFocus)?.focus({preventScroll:true});}

let celebrationKey=null,celebrationStarted=0;
function victoryCelebration(){
 const key=[state.chapter,state.turn,state.stage,state.result?.player,state.leaderResult?.won,state.govResult?.ending?.key].join(':');
 if(key!==celebrationKey){celebrationKey=key;celebrationStarted=Date.now();}
 const elapsed=(Date.now()-celebrationStarted)/1000;
 if(elapsed>=3.15)return '';
 const colors=['#ff4f7b','#ffd23f','#25bde3','#7657e8','#41cf85','#ff872e'];
 const confetti=Array.from({length:48},(_,i)=>`<i style="--x:${(i*37)%101}vw;--drift:${(i%9-4)*13}px;--delay:-${(i%12)*.11}s;--fall:${2.2+(i%7)*.16}s;--spin:${(i%2?1:-1)*(420+(i%5)*90)}deg;--color:${colors[i%colors.length]};--shape:${i%3===0?'50%':'2px'}"></i>`).join('');
 return `<div class="victory-celebration" style="--elapsed:-${elapsed}s;--exit-delay:${2.8-elapsed}s" aria-hidden="true"><div class="confetti">${confetti}</div><div class="elected-stamp"><b>当選</b><small>${term()?'再選':'確定'}</small></div></div>`;
}
function milestoneArt(id){
 const asset=window.GameScenes.milestones[id];
 return asset?`<figure class="milestone-art"><img src="${esc(asset.src)}" alt="${esc(asset.alt)}" width="1672" height="941"><figcaption><span>PHASE CLEAR</span><b>${esc(asset.label)}</b></figcaption></figure>`:'';
}
function resultUI(){
 const r=state.result,t2=state.chapter==='term2',eligible=state.nomination!=='無所属'&&state.nomination!=='公認取消'&&!state.nominationCancelled&&!state.usedRescue&&r.share>=.42;
 const eyebrow=t2?'THIRD ELECTION / 3度目の選挙':state.chapter==='term'?'SECOND ELECTION / 2度目の選挙':'ELECTION NIGHT / 投開票';
 return `${r.won?victoryCelebration():''}<div class="result ${r.won?'result-won':''}"><div class="eyebrow" style="color:#796030">${eyebrow}</div><h1>${r.won?(term()?'再選。':'当選。'):'落選。'}</h1><p>${r.won?(term()?(t2?'中堅議員としての4年間が、次の一票につながりました。':'4年間の活動が、次の一票につながりました。'):'あなたの声が、議会へ届きました。けれど、選挙中の約束はまだ終わっていません。'):'届かなかった一票。その差には、これまでの選択が積み重なっています。'}</p>
 <div class="vote-row"><span>${esc(state.name)}</span><strong>${num(r.player)}票</strong></div><div class="vote-row"><span>対抗馬</span><strong>${num(r.rival)}票</strong></div><p>得票率 ${(r.share*100).toFixed(1)}% / 差 ${num(Math.abs(r.player-r.rival))}票</p>
 ${t2&&r.party?`<div class="vote-row"><span>党の全国議席（予測）</span><strong>${r.party.seats} / ${r.party.total}</strong></div><p>党の得票率 ${(r.party.voteShare*100).toFixed(1)}%${r.party.majority?' ／ 単独過半数の勢い':' ／ 過半数には届かない'}</p>`:''}
 ${!r.won&&eligible?'<p>党から比例復活の打診が来ています。受ければ当選しますが、重さ3の借りが残ります。</p><button class="primary" data-do="rescue">比例復活を受ける →</button> ':''}
 <button class="primary" data-do="continue">${r.won&&!term()?'議員としての初日へ →':'今回の選挙を振り返る'}</button></div>`;
}
function leaderEndUI(){
 const R=state.leaderResult,e=R.ending||{label:'党首選',grade:'-',text:''},toGov=e.toGovernment;
 const bar=R.round1.map(c=>`<div class="vote-row"><span>${c.you?'▶ ':''}${esc(c.name)}</span><b>${(c.share*100).toFixed(1)}%<small> 議員${num(c.diet)}/党員${num(c.member)}</small></b></div>`).join('');
 const runoff=R.runoff?`<h3>決選投票</h3><div class="vote-row"><span>▶ あなた</span><b>${num(R.runoff.me)}</b></div><div class="vote-row"><span>${esc(R.runoffOpp)}</span><b>${num(R.runoff.opp)}</b></div><p>都道府県票 ${R.runoff.pref} / 47</p>`:'';
 return `${R.won?victoryCelebration():''}<div class="result ${R.won?'result-won':''}"><div class="eyebrow" style="color:#796030">PARTY LEADERSHIP / 党首選</div>${toGov?milestoneArt('leadership'):''}<h1>${esc(e.label)}${toGov?'':`<small style="font-size:.5em"> 評価 ${esc(e.grade)}</small>`}</h1><p>${esc(e.text)}</p>
 <h3>1回戦</h3>${bar}${runoff}
 <div class="vote-row"><span>残った借り / 踏み倒し</span><b>${state.debts.filter(d=>['未回収','一部履行'].includes(d.status)).length}件 / ${state.debts.filter(d=>d.status==='踏み倒し').length}件</b></div>
 <div class="vote-row"><span>クリーン度 / 造反</span><b>${num(state.clean)} / ${state.history.filter(h=>h.kind==='造反').length}回</b></div>
 ${!toGov&&R.score!=null?`<div class="score-line"><span>総合スコア</span><strong>${num(R.score)}</strong></div>`:''}
 ${toGov?'<button class="primary" data-do="beginGovernment">組閣に進む →</button> ':''}<button class="primary" data-do="reset">${toGov?'ここでやめる':'別の道で、もう一度 →'}</button></div>`;
}
function govEndUI(){
 const R=state.govResult,e=R.ending||{label:'終章',grade:'-',text:''};
 const cleared=['S','A','B'].includes(e.grade);
 return `${['S','A'].includes(e.grade)?victoryCelebration():''}<div class="result ${cleared?'result-won':''}"><div class="eyebrow" style="color:#796030">FINAL / 終章</div>${cleared?milestoneArt('prime_minister'):''}
 <h1>${esc(e.label)}<small style="font-size:.5em"> 評価 ${esc(e.grade)}</small></h1><p>${esc(e.text)}</p>
 ${R.seats!=null?`<div class="vote-row"><span>党の全国議席</span><b>${R.seats} / 465 ${R.soleMajority?'（単独過半数）':R.coalitionMajority?'（連立で過半数）':'（過半数割れ）'}</b></div><div class="vote-row"><span>あなたの選挙区</span><b>${R.ownWon?'議席維持':'落選'}</b></div>`:''}
 <div class="vote-row"><span>最終支持率</span><b>${num(R.finalApproval??0)}%</b></div>
 <div class="vote-row"><span>クリーン度 / 残った借り / 踏み倒し</span><b>${num(state.clean)} / ${state.debts.filter(d=>['未回収','一部履行'].includes(d.status)).length}件 / ${state.debts.filter(d=>d.status==='踏み倒し').length}件</b></div>
 <div class="vote-row"><span>造反 / 裏切った層</span><b>${state.history.filter(h=>h.kind==='造反').length}回 / ${state.memory.filter(Boolean).length}層</b></div>
 <div class="score-line"><span>総合スコア</span><strong>${num(R.score??0)}</strong></div>
 <p class="footnote">序章から終章まで、これが今回の到達点です。政党や路線を変えると、まったく違う物語になります。</p>
 <button class="primary" data-do="reset">最初から、別の物語を →</button></div>`;
}
function chapterEndUI(){
 if(state.chapter==='leadership')return leaderEndUI();
 if(state.chapter==='government')return govEndUI();
 const broken=state.debts.filter(d=>d.status==='踏み倒し').length,pending=state.debts.filter(d=>['未回収','一部履行'].includes(d.status)).length;
 const t1=state.chapter==='term',t2=state.chapter==='term2',t3=state.chapter==='term3';
 const elected=term()?state.reelected:state.elected;
 const route=term()?(state.lastElectionRescue?'比例復活':state.reelected?'選挙区で議席維持':t3&&state.term3Failed?'落選':'落選'):(state.usedRescue?'比例復活':state.elected?'選挙区で当選':'落選');
 const milestone=elected?(t3?'term3':t2?'term2':t1?'term1':'prologue'):null;
 const head=!elected?'次の一票へ。':t3?(state.leadershipSkip?'党首選は、次の機会に。':'党の顔として、ここまで。'):t2?'中堅議員、ここまで。':t1?'4年間の、その先へ。':broken?'自由にも、代償がある。':pending?'約束は、まだ続く。':'あなたの道が、始まる。';
 const body=t3?(state.term3Failed?'第3期の総選挙で議席を失い、今回の挑戦はここまでです。政党や路線を変えると、違う結末が見えてきます。':state.leadershipSkip?'派閥の長老に従い、今回の党首選は見送りました。党内での立場は保たれています。ここが今回の試作の区切りです。':'総選挙を越え、いよいよ党首選です。議員票・党員票・都道府県票をめぐる争いに挑みます。'):t2?'中堅議員としての任期を終えました。再選したら、第3期で党を率いる存在をめざします。':t1?'4年間の議員活動と再選挙を終えました。再選したら、第2期の中堅議員として次の挑戦へ進めます。':elected?'これまでの選択を引き継いで、第1期の議員活動へ進めます。':'今回の挑戦はここまで。政党や活動の配分を変えると、違う道が見えてきます。';
 return `<div class="result ${elected?'result-won':''}"><div class="eyebrow" style="color:#796030">CHAPTER COMPLETE</div>${milestone?milestoneArt(milestone):''}<h1>${head}</h1>
 <p>${body}</p>
 <div class="vote-row"><span>選挙の結果</span><b>${route}</b></div><div class="vote-row"><span>残った借り / 踏み倒し</span><b>${pending}件 / ${broken}件</b></div><div class="vote-row"><span>クリーン度</span><b>${num(state.clean)}</b></div>
 ${term()?`<div class="vote-row"><span>採決 / 造反</span><b>${state.ballots.length}回 / ${state.ballots.filter(v=>v.rebel).length}回</b></div>`:''}
 ${(t2||t3)&&state.result?.party?`<div class="vote-row"><span>党の全国議席</span><b>${state.result.party.seats} / ${state.result.party.total}${state.result.party.majority?'（単独過半数）':t3&&state.ruling?'（連立で過半数）':''}</b></div>`:''}
 ${t3&&elected?`<div class="vote-row"><span>党の立場 / あなたの役職</span><b>${state.ruling?'与党':'野党'} / ${state.cabinet==='minister'?'大臣':state.cabinet==='exec'?'党三役':'なし'}</b></div>`:''}
 ${!term()&&elected?'<button class="primary" data-do="beginTerm">第1期の議員活動へ →</button> ':''}${t1&&state.reelected?'<button class="primary" data-do="beginSecondTerm">第2期（中堅議員）へ →</button> ':''}${t2&&state.reelected?'<button class="primary" data-do="beginThirdTerm">第3期（党の顔）へ →</button> ':''}${t3&&state.reelected&&!state.leadershipSkip&&!state.term3Failed?'<button class="primary" data-do="beginLeadership">党首選に挑む →</button> ':''}<button class="primary" data-do="reset">別の道で、もう一度 →</button></div>`;
}

let careerTab='portrait';
function endUI(){
 if(!G.Career.isFinal(state))return chapterEndUI();
 const r=G.Career.summary(state),tabs=[['portrait','あなたの総括'],['history','象徴的な選択'],['result','結果の詳細']];
 const tabbar=`<nav class="career-tabs" aria-label="政治家人生の振り返り">${tabs.map(([id,label])=>`<button data-do="careerTab" data-id="${id}" aria-pressed="${careerTab===id}">${label}</button>`).join('')}</nav>`;
 if(careerTab==='result')return `<div class="career-result">${tabbar}${chapterEndUI()}</div>`;
 const layers=rows=>rows.map(x=>`<div class="career-layer"><b>${esc(x.name)}</b><span>好感度 ${num(x.value)} <small>開始時比 ${x.delta>=0?'+':''}${num(x.delta)}</small></span></div>`).join('');
 return `${state.govResult&&['S','A'].includes(state.govResult.ending?.grade)?victoryCelebration():''}<article class="career-card" aria-label="政治家人生の総括"><header>${state.govResult&&['S','A','B'].includes(state.govResult.ending?.grade)?`<div class="career-clear-art">${milestoneArt('prime_minister')}</div>`:''}<span class="eyebrow">あなたが歩んだ、政治の道</span><h1>${esc(r.title)}</h1><p class="career-trait">${esc(r.trait)}</p><div class="career-meta">当選 ${r.wins}回 ／ 最高役職：${esc(r.role)} ／ ${esc(r.ending)}</div></header>${tabbar}<div class="career-body">${careerTab==='portrait'?`<p class="career-story">${r.paragraphs.map(esc).join('')}</p><div class="career-layers"><section><h2>支持の基盤</h2>${r.supporters.length?layers(r.supporters):'<p>まだ固まっていませんでした</p>'}</section><section><h2>距離ができた人々</h2>${r.lost.length?layers(r.lost):'<p>大きく支持を失った層はありません</p>'}</section></div><p class="career-hint"><b>次の挑戦へ</b>${esc(r.hint)}</p>`:`<ol class="career-highlights">${r.highlights.map(x=>`<li><small>${esc(period(x.turn,x.chapter))} ／ ${esc(x.title)}</small><p>「${esc(x.label)}」</p></li>`).join('')||'<li>象徴的な選択を記録するには、まだ短い挑戦でした。</li>'}</ol><details><summary>活動・選挙・判定の記録を見る</summary><p>${r.actions.map(([id,n])=>esc(transitionLook[id.replace('weekend:','')]?.[1]||id)+' '+n+'回').join(' ／ ')||'活動回数の記録はありません。'}</p>${r.elections.map(e=>`<p>${esc(chapterIntros[e.chapter]?.[1]||e.chapter)}の選挙：${e.rescue?'比例復活':e.won?'当選':'落選'} ／ ${num(e.player)}票</p>`).join('')}<p>支持基盤からの推計票（最終状態）：${r.supporters.map(x=>esc(x.name)+' '+num(x.votes)+'票').join(' ／ ')||'支持基盤なし'}</p>${r.funding.map(x=>`<p>${esc(period(x.turn,x.chapter))}：${esc(x.source)} ${x.amount>0?'+':''}${num(x.amount)}万円</p>`).join('')}<p>記録された判定：成功 ${r.checks.filter(x=>x.success).length}回 ／ 失敗 ${r.checks.filter(x=>!x.success).length}回</p></details>`}${r.partial?'<p class="career-note">以前のセーブのため、残っている記録と更新後の行動から総括しています。</p>':''}</div><footer><button class="primary" data-do="reset">別の道で、もう一度 →</button></footer></article>`;
}
